---
- name: Macbook development setup
  hosts: localhost
  connection: local
  vars:
    brew_tools:
      - git
      - vim
      - nvim
      - rg
      - bat
      - tree
      - tree-sitter-cli
      - zsh-syntax-highlighting
      - zsh-autosuggestions
      - zsh-history-substring-search
      - uv
      - node
      - yarn
      - redis
      - mysql
      - rbenv
    casks:
      - ghostty
      - visual-studio-code
      - dbeaver-community

  tasks:
    - name: Install basic cli tools
      homebrew:
        name: "{{ item }}"
        state: present
      loop: "{{ brew_tools }}"

    - name: Install cask tools
      homebrew_cask:
        name: "{{ item }}"
        state: present
      loop: "{{ casks }}"

    - name: Start Redis
      community.general.homebrew_services:
        name: redis
        state: started

    - name: Start MySQL
      community.general.homebrew_services:
        name: mysql
        state: started

    - name: Initialize rbenv
      command: "rbenv init"

    - name: Install Ruby 3.4.4
      command: "rbenv install 3.4.4"

    - name: Set Ruby 3.4.4 as global
      command: "rbenv global 3.4.4"

    - name: Install Rails 8.0.2
      command: "gem install rails -v 8.0.2 --no-document"

    - name: Install TypeScript
      command: "sudo npm i -g typescript"

    - name: Install Yeoman and VS Code generator
      command: "npm install -g yo generator-code"

    - name: Install VS Code Extension Manager
      command: "npm install -g vsce"

    - name: Install Python 3.14
      command: "uv python install 3.14"

    - name: Pin Python 3.14
      command: "uv python pin 3.14"

    - name: Install Python 3.13
      command: "uv python install 3.13"
