---
- name: Personalise setup
  hosts: localhost
  connection: local

  vars:
    src_dir_name: dotfiles
    src_dir_path: "{{ ansible_env.HOME }}/src/{{ src_dir_name }}"

  tasks:

    - name: Set key repeat - highest rate, lowest delay
      osx_defaults:
        domain: NSGlobalDomain
        key: "{{ item.key }}"
        type: float
        value: "{{ item.value }}"
        state: present
      loop:
        - { key: KeyRepeat, value: 2 }
        - { key: InitialKeyRepeat, value: 15 }

    - name: Create a base dir for all source code
      file:
        path: "{{ ansible_env.HOME }}/src"
        state: directory

    - name: Clone the dotfiles repo
      git:
        repo: "git@github.com:ayushkpai/dotfiles.git"
        dest: "{{ src_dir_path }}"

    - name: symlink gitignore_global file
      file:
        src: "{{ src_dir_path }}/gitignore_global"
        dest: "{{ ansible_env.HOME }}/.gitignore_global"
        state: link

    - name: Configure Git user
      prompt:
        - name: Git user name
          variable: name
        - name: Git email
          variable: email
      commands:
        - 'git config --global user.name "{{ name }}"'
        - 'git config --global user.email "{{ email }}"'
        - "git config --global core.autocrlf input"
        - "git config --global core.excludesfile ~/.gitignore_global"

    - name: symlink zshrc file
      file:
        src: "{{ src_dir_path }}/zshrc"
        dest: "{{ ansible_env.HOME }}/.zshrc"
        state: link

    - name: Setup nvim & ghostty configs
      file:
        src: "{{ src_dir_path }}/{{ item }}"
        dest: "{{ ansible_env.HOME }}/.config/{{ item }}"
        state: link
      loop:
        - nvim
        - ghostty
