#!/usr/bin/env ruby

unless system("/opt/homebrew/bin/brew -v")
  puts "Installing homebrew..."
  system %{/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"}
end

unless system("/opt/homebrew/bin/ansible --version")
  puts "Installing ansible..."
  system "/opt/homebrew/bin/brew install ansible"
end

unless Dir.exist?("/tmp/jumpstart/")
  puts "Downloading jumpstart..."
  system "git clone https://github.com/ayushkpai/jumpstart.git /tmp/jumpstart"
end

system "cd /tmp/jumpstart && /opt/homebrew/bin/ansible-playbook 0-test.yml"
