#!/usr/bin/env ruby

src = File.expand_path("~/src")
dotfiles = File.join(src, "dotfiles")
config = File.expand_path("~/.config")
ghostty = File.join(config, "ghostty")
nvim = File.join(config, "nvim")

def run(command)
  puts "→ #{command}"
  system(command) or abort("Command failed: #{command}")
end

unless Dir.exist?(src)
  puts "Creating #{src}"
  Dir.mkdir(src)
end

unless Dir.exist?(dotfiles)
  run("git clone git@github.com:ayushkpai/dotfiles.git #{dotfiles}")
else
  puts "#{dotfiles} already exists, skipping clone"
end

unless Dir.exist?(config)
  puts "Creating #{config}"
  Dir.mkdir(config)
else
  puts "#{config} already exists, skipping"
end

unless File.exist?(ghostty) || File.symlink?(ghostty)
  run("ln -s #{File.join(dotfiles, "ghostty")} #{ghostty}")
else
  puts "#{ghostty} already exists, skipping symlink"
end

unless File.exist?(nvim) || File.symlink?(nvim)
  run("ln -s #{File.join(dotfiles, "nvim")} #{nvim}")
else
  puts "#{nvim} already exists, skipping symlink"
end

run(%q{sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"})
run("echo source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh >> ~/.zshrc")
run("echo source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh >> ~/.zshrc")
run("echo source /opt/homebrew/share/zsh-history-substring-search/zsh-history-substring-search.zsh >> ~/.zshrc")

print "Git user name: "
name = gets.chomp

print "Git email: "
email = gets.chomp

run(%(git config --global user.name "#{name}"))
run(%(git config --global user.email "#{email}"))
run("git config --global core.autocrlf input")

run("rbenv init")
run("rbenv install 3.4.4")
run("rbenv global 3.4.4")
run("gem install rails -v 8.0.2 --no-document")
run("sudo npm i -g typescript")
run("npm install -g yo generator-code")
run("npm install -g vsce")
run("uv python install 3.14")
run("uv python pin 3.14")
run("uv python install 3.13")
